os: osx
language: generic
osx_image: xcode9.0
before_script:
  - pip2 install six
  - brew update
  # - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - brew cask install fastlane
  - git clone https://github.com/flutter/flutter.git
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
  - cd ios
  - bundle update fastlane
  - cd ../
script:
  - ./flutter/bin/flutter build ios --release --no-codesign
  - cd ios
  - fastlane custom_lane
cache:
  directories:
    - $HOME/.pub-cache