# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    xcversion(version: "9.4.1")
    enable_automatic_code_signing(
      path: "Runner.xcodeproj"
    )
    # add actions here: https://docs.fastlane.tools/actions
    build_app(scheme: "Runner",
      workspace: "Runner.xcworkspace",
      include_bitcode: true)    
  end
end
